routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});


Auth::routes();

Route::get('/home', 'HomeController@index');

Route::resource('users', 'UserController');

Route::resource('workers', 'WorkerController');

Route::resource('spaceTypes', 'SpaceTypeController');

Route::resource('spaces', 'SpaceController');

Route::resource('shiftTypes', 'ShiftTypeController');

Route::resource('roles', 'RoleController');

Route::resource('reservations', 'ReservationController');

Route::resource('payments', 'PaymentController');

Route::resource('maintenances', 'MaintenanceController');

Route::resource('maintainers', 'MaintainerController');

Route::resource('expenses', 'ExpenseController');

Route::resource('calendars', 'CalendarController');

Route::resource('buildings', 'BuildingController');

Route::resource('assistances', 'AssistanceController');

Route::resource('articles', 'ArticleController');

Route::resource('apartments', 'ApartmentController');

app/Http/Controllers/ShiftTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ShiftTypeDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateShiftTypeRequest;
use App\Http\Requests\UpdateShiftTypeRequest;
use App\Repositories\ShiftTypeRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ShiftTypeController extends AppBaseController
{
    /** @var  ShiftTypeRepository */
    private $shiftTypeRepository;

    public function __construct(ShiftTypeRepository $shiftTypeRepo)
    {
        $this->shiftTypeRepository = $shiftTypeRepo;
    }

    /**
     * Display a listing of the ShiftType.
     *
     * @param ShiftTypeDataTable $shiftTypeDataTable
     * @return Response
     */
    public function index(ShiftTypeDataTable $shiftTypeDataTable)
    {
        return $shiftTypeDataTable->render('shift_types.index');
    }

    /**
     * Show the form for creating a new ShiftType.
     *
     * @return Response
     */
    public function create()
    {
        return view('shift_types.create');
    }

    /**
     * Store a newly created ShiftType in storage.
     *
     * @param CreateShiftTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateShiftTypeRequest $request)
    {
        $input = $request->all();

        $shiftType = $this->shiftTypeRepository->create($input);

        Flash::success('Shift Type saved successfully.');

        return redirect(route('shiftTypes.index'));
    }

    /**
     * Display the specified ShiftType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $shiftType = $this->shiftTypeRepository->findWithoutFail($id);

        if (empty($shiftType)) {
            Flash::error('Shift Type not found');

            return redirect(route('shiftTypes.index'));
        }

        return view('shift_types.show')->with('shiftType', $shiftType);
    }

    /**
     * Show the form for editing the specified ShiftType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $shiftType = $this->shiftTypeRepository->findWithoutFail($id);

        if (empty($shiftType)) {
            Flash::error('Shift Type not found');

            return redirect(route('shiftTypes.index'));
        }

        return view('shift_types.edit')->with('shiftType', $shiftType);
    }

    /**
     * Update the specified ShiftType in storage.
     *
     * @param  int              $id
     * @param UpdateShiftTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateShiftTypeRequest $request)
    {
        $shiftType = $this->shiftTypeRepository->findWithoutFail($id);

        if (empty($shiftType)) {
            Flash::error('Shift Type not found');

            return redirect(route('shiftTypes.index'));
        }

        $shiftType = $this->shiftTypeRepository->update($request->all(), $id);

        Flash::success('Shift Type updated successfully.');

        return redirect(route('shiftTypes.index'));
    }

    /**
     * Remove the specified ShiftType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $shiftType = $this->shiftTypeRepository->findWithoutFail($id);

        if (empty($shiftType)) {
            Flash::error('Shift Type not found');

            return redirect(route('shiftTypes.index'));
        }

        $this->shiftTypeRepository->delete($id);

        Flash::success('Shift Type deleted successfully.');

        return redirect(route('shiftTypes.index'));
    }
}

resources/views/shift_types/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Shift Type
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'shiftTypes.store']) !!}

                        @include('shift_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shift_types/datatables_actions.blade.php
{!! Form::open(['route' => ['shiftTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('shiftTypes.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('shiftTypes.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/shift_types/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Shift Type
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($shiftType, ['route' => ['shiftTypes.update', $shiftType->id], 'method' => 'patch']) !!}

                        @include('shift_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/shift_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('shiftTypes.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/shift_types/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Shift Types</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('shiftTypes.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('shift_types.table')
            </div>
        </div>
    </div>
@endsection

resources/views/shift_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Shift Type
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('shift_types.show_fields')
                    <a href="{!! route('shiftTypes.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/shift_types/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $shiftType->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $shiftType->name !!}</p>
</div>

resources/views/shift_types/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection